/**
 * Layered map reveal configs — one entry per map that supports room toggles.
 *
 * Layer PNGs are generated by:
 *   npm run generate-map-layers -- <mapId>
 */

export const DEATH_HOUSE_BASEMENT_MAP_ID = "death-house-basement";
export const DEATH_HOUSE_DUNGEON_LEVEL_MAP_ID = "death-house-dungeon-level";

export const MAP_REVEAL_CONFIGS = {
  [DEATH_HOUSE_BASEMENT_MAP_ID]: {
    mapId: DEATH_HOUSE_BASEMENT_MAP_ID,
    panelLabel: "Death House",
    darkBase: "/maps/death-house-basement/layers/dark-base.png",
    manifest: "/maps/death-house-basement/layers/manifest.json",
    sourceMap: "/maps/death-house-basement.png",
    regionIds: [23, 24, 25, 26, 27, 29, 30, 31, 33, 34],
    /** Toggling this region lights the entire map (no unrevealed black). */
    fullRevealRegionId: 34,
  },
  [DEATH_HOUSE_DUNGEON_LEVEL_MAP_ID]: {
    mapId: DEATH_HOUSE_DUNGEON_LEVEL_MAP_ID,
    panelLabel: "Dungeon Level",
    darkBase: "/maps/death-house-dungeon-level/layers/dark-base.png",
    manifest: "/maps/death-house-dungeon-level/layers/manifest.json",
    sourceMap: "/maps/death-house-dungeon-level.png",
    regionIds: [35, 36, 37],
    /** Toggling this region lights the entire map (no unrevealed black). */
    fullRevealRegionId: 37,
  },
};

export function getMapRevealConfig(mapId) {
  return MAP_REVEAL_CONFIGS[mapId] || null;
}

export function isMapRevealMap(mapId) {
  return Boolean(getMapRevealConfig(mapId));
}

export function getMapRevealRegionIds(mapId) {
  return getMapRevealConfig(mapId)?.regionIds || [];
}

export function getFullRevealRegionId(mapId) {
  const fullRevealRegionId = getMapRevealConfig(mapId)?.fullRevealRegionId;
  return Number.isFinite(fullRevealRegionId) ? fullRevealRegionId : null;
}

export function isFullMapRevealActive(mapId, revealedRegions) {
  const fullRevealRegionId = getFullRevealRegionId(mapId);
  if (fullRevealRegionId == null || !Array.isArray(revealedRegions)) {
    return false;
  }
  return revealedRegions.includes(fullRevealRegionId);
}

export function normalizeMapRevealRegions(rawRegions, mapId) {
  if (!Array.isArray(rawRegions)) return [];
  const allowed = new Set(getMapRevealRegionIds(mapId));
  const revealed = [];
  for (const entry of rawRegions) {
    const regionId = Number(entry);
    if (allowed.has(regionId) && !revealed.includes(regionId)) {
      revealed.push(regionId);
    }
  }
  return revealed.sort((left, right) => left - right);
}

export function createDefaultMapRevealState() {
  return {
    enabled: true,
    revealedRegions: [],
  };
}

export function normalizeMapRevealState(raw = {}, mapId = "") {
  if (!isMapRevealMap(mapId)) {
    return null;
  }
  return {
    enabled: raw.enabled !== false,
    revealedRegions: normalizeMapRevealRegions(raw.revealedRegions, mapId),
  };
}
