/**
 * D&D creature voices built from layered DSP rather than samples.
 *
 * Layer macros (0–1 unless noted):
 *   pitch     semitones of the main body voice
 *   formant   semitones of vocal-tract size (negative = bigger throat)
 *   sub       octave-down weight (mass, chest)
 *   detune    doubled voice (thickness, "more than one speaker")
 *   ring      inharmonic shimmer via frequency shifting (alien / metallic)
 *   ringFreq  Hz of that shift
 *   growl     throat roughness via 25–90 Hz amplitude modulation
 *   growlRate Hz of the growl
 *   air       breath noise opened by your own voice envelope
 *   airFreq   Hz centre of that breath
 *   drive     saturation
 *
 * Tone: low / mid / high (dB), presence (+dB at presenceFreq)
 * Space: chorus / vibrato / delay / reverb
 * Range: highpass / lowpass (Hz), gain
 */

export const VOICE_PRESET_VERSION = 4;

export const DEFAULT_VOICE_PARAMS = {
  pitch: 0,
  formant: 0,
  sub: 0,
  detune: 0,
  ring: 0,
  ringFreq: 40,
  growl: 0,
  growlRate: 55,
  air: 0,
  airFreq: 3200,
  drive: 0,
  low: 0,
  mid: 0,
  high: 0,
  presence: 3,
  presenceFreq: 2200,
  chorus: 0,
  vibrato: 0,
  delay: 0,
  reverb: 0.08,
  highpass: 85,
  lowpass: 12000,
  gain: 1.2,
};

function preset(id, name, category, overrides) {
  return { id, name, category, ...DEFAULT_VOICE_PARAMS, ...overrides };
}

export const voicePresets = [
  // ——— Dragons ———
  preset("chromatic-dragons", "Chromatic Dragons", "Dragons", {
    pitch: -4,
    formant: -5,
    sub: 0.55,
    growl: 0.38,
    growlRate: 58,
    drive: 0.34,
    air: 0.1,
    airFreq: 2400,
    low: 2,
    mid: 3,
    high: -1,
    presence: 5,
    presenceFreq: 1800,
    reverb: 0.18,
    delay: 0.05,
    lowpass: 6800,
    gain: 1.4,
  }),
  preset("metallic-dragons", "Metallic Dragons", "Dragons", {
    pitch: -3,
    formant: -3,
    sub: 0.34,
    detune: 0.32,
    ring: 0.14,
    ringFreq: 28,
    growl: 0.14,
    growlRate: 44,
    drive: 0.16,
    low: 0,
    mid: 2,
    high: 3,
    presence: 4,
    presenceFreq: 2500,
    chorus: 0.22,
    reverb: 0.3,
    delay: 0.1,
    lowpass: 8600,
    gain: 1.3,
  }),
  preset("ancient-dragons", "Ancient Dragons", "Dragons", {
    pitch: -5,
    formant: -8,
    sub: 0.72,
    growl: 0.18,
    growlRate: 34,
    drive: 0.16,
    low: 3,
    mid: 1,
    high: -2,
    presence: 5,
    presenceFreq: 1550,
    chorus: 0.1,
    reverb: 0.46,
    delay: 0.26,
    lowpass: 6200,
    gain: 1.45,
  }),

  // ——— Fiends ———
  preset("demons", "Demons", "Fiends", {
    pitch: -4,
    formant: -4,
    sub: 0.5,
    detune: 0.48,
    ring: 0.08,
    ringFreq: 33,
    growl: 0.46,
    growlRate: 72,
    drive: 0.44,
    mid: 4,
    high: -1,
    presence: 4,
    presenceFreq: 1650,
    reverb: 0.22,
    delay: 0.08,
    lowpass: 6600,
    gain: 1.35,
  }),
  preset("devils", "Devils", "Fiends", {
    pitch: -2,
    formant: -2,
    sub: 0.22,
    detune: 0.26,
    drive: 0.18,
    mid: 3,
    high: 2,
    presence: 5,
    presenceFreq: 2300,
    chorus: 0.12,
    reverb: 0.16,
    delay: 0.05,
    lowpass: 8200,
    gain: 1.25,
  }),

  // ——— Humanoids ———
  preset("goblins", "Goblins", "Humanoids", {
    pitch: 7,
    formant: 6,
    growl: 0.16,
    growlRate: 88,
    air: 0.12,
    airFreq: 4200,
    drive: 0.14,
    low: -6,
    mid: 4,
    high: 4,
    presence: 4,
    presenceFreq: 2900,
    vibrato: 0.08,
    reverb: 0.06,
    highpass: 200,
    lowpass: 9500,
    gain: 1.2,
  }),
  preset("hobgoblins", "Hobgoblins", "Humanoids", {
    pitch: 1,
    formant: -1,
    drive: 0.18,
    growl: 0.1,
    growlRate: 62,
    low: 1,
    mid: 5,
    high: -1,
    presence: 6,
    presenceFreq: 1900,
    reverb: 0.04,
    lowpass: 7200,
    gain: 1.3,
  }),
  preset("kobolds", "Kobolds", "Humanoids", {
    pitch: 9,
    formant: 8,
    air: 0.1,
    airFreq: 4800,
    low: -8,
    mid: 3,
    high: 5,
    presence: 3,
    presenceFreq: 3300,
    vibrato: 0.14,
    reverb: 0.05,
    highpass: 240,
    lowpass: 9800,
    gain: 1.15,
  }),
  preset("orcs", "Orcs", "Humanoids", {
    pitch: -3,
    formant: -3,
    sub: 0.3,
    growl: 0.32,
    growlRate: 66,
    drive: 0.3,
    low: 2,
    mid: 3,
    high: -2,
    presence: 4,
    presenceFreq: 1750,
    reverb: 0.09,
    lowpass: 6800,
    gain: 1.35,
  }),
  preset("ogres", "Ogres", "Humanoids", {
    pitch: -4,
    formant: -6,
    sub: 0.5,
    growl: 0.24,
    growlRate: 44,
    drive: 0.2,
    low: 3,
    mid: 3,
    high: -1,
    presence: 7,
    presenceFreq: 1650,
    reverb: 0.12,
    delay: 0.04,
    lowpass: 6600,
    gain: 1.5,
  }),
  preset("trolls", "Trolls", "Humanoids", {
    pitch: -3,
    formant: -4,
    sub: 0.28,
    growl: 0.42,
    growlRate: 50,
    air: 0.16,
    airFreq: 2600,
    drive: 0.32,
    mid: 4,
    high: -3,
    presence: 4,
    presenceFreq: 1500,
    reverb: 0.14,
    lowpass: 6200,
    gain: 1.35,
  }),
  preset("giants", "Giants", "Humanoids", {
    pitch: -5,
    formant: -9,
    sub: 0.66,
    growl: 0.1,
    growlRate: 30,
    drive: 0.1,
    low: 3,
    mid: 1,
    high: 0,
    presence: 6,
    presenceFreq: 1500,
    chorus: 0.06,
    reverb: 0.34,
    delay: 0.2,
    lowpass: 6400,
    gain: 1.5,
  }),

  // ——— Undead ———
  preset("liches", "Liches", "Undead", {
    pitch: -1,
    formant: -2,
    detune: 0.38,
    ring: 0.12,
    ringFreq: 21,
    air: 0.26,
    airFreq: 3600,
    drive: 0.06,
    low: -5,
    mid: 1,
    high: 4,
    presence: 3,
    presenceFreq: 2700,
    chorus: 0.32,
    reverb: 0.5,
    delay: 0.2,
    highpass: 150,
    lowpass: 8800,
    gain: 1.2,
  }),
  preset("vampires", "Vampires", "Undead", {
    pitch: -1,
    formant: -1,
    air: 0.14,
    airFreq: 3000,
    low: 1,
    mid: 2,
    high: 1,
    presence: 4,
    presenceFreq: 2100,
    chorus: 0.1,
    reverb: 0.24,
    delay: 0.06,
    lowpass: 8000,
    gain: 1.2,
  }),
  preset("zombies", "Zombies", "Undead", {
    pitch: -3,
    formant: -4,
    growl: 0.34,
    growlRate: 26,
    air: 0.22,
    airFreq: 2200,
    drive: 0.16,
    low: 1,
    mid: -1,
    high: -3,
    presence: 5,
    presenceFreq: 1700,
    vibrato: 0.2,
    reverb: 0.12,
    lowpass: 5600,
    gain: 1.4,
  }),
  preset("skeletons", "Skeletons", "Undead", {
    pitch: 5,
    formant: 5,
    ring: 0.2,
    ringFreq: 64,
    air: 0.3,
    airFreq: 5200,
    drive: 0.2,
    low: -11,
    mid: -2,
    high: 7,
    presence: 2,
    presenceFreq: 3500,
    chorus: 0.1,
    reverb: 0.18,
    highpass: 330,
    lowpass: 9800,
    gain: 1.2,
  }),
  preset("necromancers", "Necromancers", "Undead", {
    pitch: -2,
    formant: -3,
    detune: 0.44,
    ring: 0.06,
    ringFreq: 17,
    air: 0.18,
    airFreq: 2800,
    drive: 0.1,
    low: -2,
    mid: 3,
    high: 1,
    presence: 3,
    presenceFreq: 2300,
    chorus: 0.26,
    reverb: 0.44,
    delay: 0.24,
    lowpass: 7400,
    gain: 1.22,
  }),

  // ——— Aberrations ———
  preset("beholders", "Beholders", "Aberrations", {
    pitch: -2,
    formant: 1,
    ring: 0.32,
    ringFreq: 47,
    growl: 0.2,
    growlRate: 24,
    mid: 5,
    high: 0,
    presence: 3,
    presenceFreq: 1850,
    chorus: 0.18,
    reverb: 0.26,
    delay: 0.1,
    lowpass: 7000,
    gain: 1.25,
  }),
  preset("mind-flayers", "Mind Flayers", "Aberrations", {
    pitch: 0,
    formant: -1,
    ring: 0.36,
    ringFreq: -38,
    air: 0.36,
    airFreq: 3800,
    low: -4,
    mid: 5,
    high: 3,
    presence: 4,
    presenceFreq: 2500,
    chorus: 0.3,
    vibrato: 0.12,
    reverb: 0.36,
    delay: 0.16,
    highpass: 140,
    lowpass: 8400,
    gain: 1.2,
  }),

  // ——— Fey & Celestials ———
  preset("fairies", "Fairies", "Fey & Celestials", {
    pitch: 8,
    formant: 7,
    air: 0.12,
    airFreq: 5600,
    low: -10,
    mid: 2,
    high: 7,
    presence: 3,
    presenceFreq: 3600,
    chorus: 0.36,
    vibrato: 0.18,
    reverb: 0.32,
    delay: 0.08,
    highpass: 280,
    lowpass: 11000,
    gain: 1.12,
  }),
  preset("angels", "Angels", "Fey & Celestials", {
    pitch: 2,
    formant: 2,
    detune: 0.32,
    air: 0.12,
    airFreq: 4200,
    low: -3,
    mid: 1,
    high: 5,
    presence: 3,
    presenceFreq: 2800,
    chorus: 0.28,
    reverb: 0.5,
    delay: 0.12,
    highpass: 130,
    lowpass: 10500,
    gain: 1.18,
  }),
  preset("celestials", "Celestials", "Fey & Celestials", {
    pitch: 1,
    formant: 0,
    detune: 0.4,
    ring: 0.05,
    ringFreq: 12,
    low: -1,
    mid: 2,
    high: 4,
    presence: 3,
    presenceFreq: 2600,
    chorus: 0.32,
    reverb: 0.56,
    delay: 0.14,
    lowpass: 10500,
    gain: 1.18,
  }),

  // ——— Elemental & Sea ———
  preset("elementals", "Elementals", "Elemental & Sea", {
    pitch: -1,
    formant: -2,
    ring: 0.2,
    ringFreq: 19,
    growl: 0.2,
    growlRate: 38,
    air: 0.24,
    airFreq: 3000,
    drive: 0.14,
    mid: 2,
    high: 3,
    presence: 3,
    presenceFreq: 2400,
    chorus: 0.24,
    reverb: 0.4,
    delay: 0.1,
    lowpass: 8600,
    gain: 1.28,
  }),
  preset("kraken", "Kraken", "Elemental & Sea", {
    pitch: -5,
    formant: -7,
    sub: 0.6,
    growl: 0.22,
    growlRate: 29,
    air: 0.16,
    airFreq: 1800,
    drive: 0.2,
    low: 2,
    mid: 4,
    high: -1,
    presence: 6,
    presenceFreq: 1550,
    chorus: 0.3,
    reverb: 0.4,
    delay: 0.2,
    lowpass: 6200,
    gain: 1.45,
  }),
  preset("sea-serpents", "Sea Serpents", "Elemental & Sea", {
    pitch: -2,
    formant: 0,
    ring: 0.14,
    ringFreq: 57,
    air: 0.48,
    airFreq: 5000,
    drive: 0.12,
    low: -3,
    mid: 2,
    high: 4,
    presence: 3,
    presenceFreq: 2800,
    chorus: 0.32,
    vibrato: 0.2,
    reverb: 0.3,
    delay: 0.1,
    highpass: 145,
    lowpass: 9000,
    gain: 1.3,
  }),

  // ——— People ———
  preset("wizards", "Wizards", "People", {
    pitch: -1,
    formant: -1,
    low: -2,
    mid: 3,
    high: 2,
    presence: 3,
    presenceFreq: 2300,
    chorus: 0.08,
    reverb: 0.22,
    delay: 0.08,
    lowpass: 8600,
    gain: 1.2,
  }),
  preset("kings", "Kings", "People", {
    pitch: -2,
    formant: -3,
    sub: 0.2,
    low: 3,
    mid: 2,
    high: 0,
    presence: 4,
    presenceFreq: 1800,
    reverb: 0.14,
    delay: 0.04,
    lowpass: 7600,
    gain: 1.28,
  }),
  preset("queens", "Queens", "People", {
    pitch: 5,
    formant: 6,
    air: 0.12,
    airFreq: 4600,
    low: -6,
    mid: 2,
    high: 5,
    presence: 4,
    presenceFreq: 3000,
    chorus: 0.14,
    vibrato: 0.05,
    reverb: 0.2,
    highpass: 170,
    lowpass: 10200,
    gain: 1.2,
  }),
  preset("merchants", "Merchants", "People", {
    pitch: 0,
    formant: 1,
    mid: 2,
    high: 1,
    presence: 3,
    presenceFreq: 2200,
    reverb: 0.05,
    lowpass: 9000,
    gain: 1.15,
  }),
  preset("guards", "Guards", "People", {
    pitch: -1,
    formant: -2,
    drive: 0.06,
    low: 2,
    mid: 3,
    high: -1,
    presence: 4,
    presenceFreq: 1900,
    reverb: 0.05,
    lowpass: 7200,
    gain: 1.28,
  }),
  preset("innkeepers", "Innkeepers", "People", {
    pitch: 0,
    formant: -1,
    low: 2,
    mid: 1,
    high: 0,
    presence: 3,
    presenceFreq: 2000,
    reverb: 0.08,
    lowpass: 8200,
    gain: 1.18,
  }),
  preset("bandits", "Bandits", "People", {
    pitch: -1,
    formant: -1,
    growl: 0.1,
    growlRate: 70,
    drive: 0.14,
    mid: 3,
    high: -1,
    presence: 4,
    presenceFreq: 2000,
    reverb: 0.06,
    lowpass: 7200,
    gain: 1.22,
  }),
  // Deep, close, dry and breathy — the cowl-and-gravel delivery.
  preset("assassins", "Assassins", "People", {
    pitch: -5,
    formant: -4,
    sub: 0.38,
    growl: 0.12,
    growlRate: 40,
    air: 0.2,
    airFreq: 2000,
    drive: 0.12,
    low: 3,
    mid: 2,
    high: -4,
    presence: 5,
    presenceFreq: 1400,
    reverb: 0.06,
    delay: 0.02,
    lowpass: 5400,
    gain: 1.38,
  }),
  // Many voices speaking as one.
  preset("cultists", "Cultists", "People", {
    pitch: -3,
    formant: -3,
    detune: 0.55,
    ring: 0.08,
    ringFreq: 23,
    growl: 0.16,
    growlRate: 42,
    air: 0.18,
    airFreq: 2400,
    drive: 0.24,
    mid: 5,
    high: -2,
    presence: 3,
    presenceFreq: 1600,
    chorus: 0.26,
    reverb: 0.42,
    delay: 0.24,
    lowpass: 6400,
    gain: 1.32,
  }),

  // ——— Beasts ———
  preset("yeti", "Yeti", "Beasts", {
    pitch: -4,
    formant: -5,
    sub: 0.44,
    growl: 0.3,
    growlRate: 48,
    air: 0.22,
    airFreq: 2600,
    drive: 0.18,
    low: 2,
    mid: 2,
    high: -2,
    presence: 5,
    presenceFreq: 1500,
    reverb: 0.16,
    lowpass: 6200,
    gain: 1.42,
  }),
  preset("bats", "Bats", "Beasts", {
    pitch: 10,
    formant: 9,
    ring: 0.16,
    ringFreq: 76,
    air: 0.26,
    airFreq: 6400,
    low: -12,
    mid: -1,
    high: 8,
    presence: 2,
    presenceFreq: 4000,
    vibrato: 0.16,
    reverb: 0.12,
    highpass: 360,
    lowpass: 11000,
    gain: 1.1,
  }),
  preset("wolves", "Wolves / Stags", "Beasts", {
    pitch: -2,
    formant: -3,
    growl: 0.48,
    growlRate: 61,
    air: 0.16,
    airFreq: 2800,
    drive: 0.28,
    low: 1,
    mid: 5,
    high: -1,
    presence: 6,
    presenceFreq: 1750,
    reverb: 0.1,
    lowpass: 7000,
    gain: 1.4,
  }),

  // ——— Utility ———
  preset("narrator", "Narrator (warm)", "Utility", {
    pitch: -1,
    formant: -2,
    sub: 0.14,
    low: 2,
    mid: 1,
    high: 1,
    presence: 4,
    presenceFreq: 2100,
    reverb: 0.1,
    lowpass: 9500,
    gain: 1.25,
  }),
  preset("whisper", "Whisper (secrets)", "Utility", {
    pitch: 0,
    formant: 1,
    air: 0.62,
    airFreq: 4400,
    low: -8,
    mid: 0,
    high: 4,
    presence: 3,
    presenceFreq: 3000,
    reverb: 0.2,
    highpass: 220,
    lowpass: 9000,
    gain: 1.3,
  }),
  preset("clean", "Clean (no FX)", "Utility", {
    pitch: 0,
    formant: 0,
    presence: 0,
    reverb: 0,
    highpass: 60,
    lowpass: 16000,
    gain: 1.1,
  }),
];

export const defaultVoiceByCharacterId = {
  "shadow-demon": "demons",
  spider: "elementals",
};

export function getVoicePresetById(presetId) {
  return voicePresets.find((preset) => preset.id === presetId) || null;
}

export function getVoiceCategories() {
  const categories = [];
  const seen = new Set();
  for (const preset of voicePresets) {
    if (seen.has(preset.category)) continue;
    seen.add(preset.category);
    categories.push(preset.category);
  }
  return categories;
}

export function resolveVoiceParams(basePreset, overrides = {}) {
  return {
    ...DEFAULT_VOICE_PARAMS,
    ...(basePreset || {}),
    ...overrides,
    id: overrides.id || basePreset?.id || "custom",
    name: overrides.name || basePreset?.name || "Custom",
    category: overrides.category || basePreset?.category || "Custom",
  };
}
